### ISSUE TITLE
Array to string conversion (View: /Users/Sites/localhost/laravel-8-template/resources/views/stisla/crud-example/index.blade.php)

### ISSUE THREAD

**Issue by aanelzam93** [Anamcoollzz/laravel-8-template#23]
error if data contain of file like .json and other
![Screenshot 2023-02-23 at 20 42 25](https://user-images.githubusercontent.com/7748917/220924087-c88bb004-d6d9-437c-a7be-23fc193e4929.png)

**Comment by andridarmawandotcom** [comment]
problem nya sama ketika membuat contoh 1 crud,mungkin bisa diberi tutorial nya om :)
thanks you

**Comment by Anamcoollzz** [comment]
Okay thanks guys atas feedbacknya, nanti aku cek terlebih dahulu

**Comment by andridarmawandotcom** [comment]
okey om,
seep, thanks you ditunggu update nya

**Comment by Anamcoollzz** [comment]
Bisa dicoba kembali ya @andridarmawandotcom @aanelzam93
