### ISSUE TITLE
List Backup Database tidak muncul

### ISSUE THREAD

**Issue by ombapit** [Anamcoollzz/laravel-8-template#27]
List backup tidak muncul, padahal sudah ada datanya

**Comment by Anamcoollzz** [comment]
Bisa bantu screenshot @ombapit ?

**Comment by ombapit** [comment]
![image](https://user-images.githubusercontent.com/2478584/221953133-b7841bb3-32d4-4333-9a87-a66a82a39bb6.png)

berikut captureannya. 
1. sudah klik tombol Backup sekarang
2. di dashboard ada countnya
3. dilistnya tidak ada

**Comment by Anamcoollzz** [comment]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/26503196/222954836-5344778f-e71c-4305-8675-a8fc09328d57.png">
Anda @ombapit bisa melihat di storage/app/public/database-backups 
disana tertera waktu backupnya, jadi bisa difilter berdasarkan tahun dan bulannya ya

**Comment by ombapit** [comment]
ok mas, tapi nomer 3 masih belum tampil. atau jika tidak perlu, bisa dihapus saja dari UI.

**Comment by Anamcoollzz** [comment]
Bisa bantu screenshot lagi maksudnya gmn ya?

**Comment by ombapit** [comment]
> ![image](https://user-images.githubusercontent.com/2478584/221953133-b7841bb3-32d4-4333-9a87-a66a82a39bb6.png)
> 
> berikut captureannya.
> 
>     1. sudah klik tombol Backup sekarang
> 
>     2. di dashboard ada countnya
> 
>     3. dilistnya tidak ada

capturenya tetap yang ini. Walau sudah ada hasilnya, di ui point 3 listnya tetep blank (tidak ada data)
