### ISSUE TITLE
Registration not working well

### ISSUE THREAD

**Issue by faisalachmadf** [Anamcoollzz/laravel-8-template#28]
i try to Regist a new Account, but its not working, any advice?
thx

**Comment by Anamcoollzz** [comment]
can you share proof of screenshot?

**Comment by andridarmawandotcom** [comment]
register new account not function, only stuck after submit data

**Comment by faisalachmadf** [comment]
when i try to fill a form registration and then i'm click Daftar Akun, Its Not Working, just give respon link '#',

**Comment by ombapit** [comment]
ill help to capture the problem.
![image](https://user-images.githubusercontent.com/2478584/222941778-780f26eb-9372-455d-8971-76ca1469000c.png)

**Comment by Anamcoollzz** [comment]
Thanks everyone, i have fix the issue, you can pull latest code

**Comment by ombapit** [comment]
Registration success, but still more bugs on there.
1. Logs failed to create after register, it throw an exception
2. Logs failed to create after verify, it throw an exception
3. Failed to resend email verification on this route: auth/send-email-verification
4. Logs failed after submit email verification, it throw an exception
5. Logs failed after submit forgot password, it throw an exception
6. Account created doesnt have default role.
