### ISSUE TITLE
Registration success, but still more bugs on there.

### ISSUE THREAD

**Issue by ombapit** [Anamcoollzz/laravel-8-template#31]
Registration success, but still more bugs on there.
1. Logs failed to create after register, it throw an exception
2. Logs failed to create after verify, it throw an exception
3. Failed to resend email verification on this route: auth/send-email-verification
4. Logs failed after submit email verification, it throw an exception
5. Logs failed after submit forgot password, it throw an exception
6. Account created doesnt have default role.

_Originally posted by @ombapit in https://github.com/Anamcoollzz/laravel-8-template/issues/28#issuecomment-1455163692_

**Comment by Anamcoollzz** [comment]
Sudah diset untuk smtp nya kah @ombapit ? coba diset terlebih dahulu, aku pake mailtrap aman
